version: "3.5"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - '3000:3000'

  graphite_statsd:
    image: graphiteapp/docker-graphite-statsd:latest
    container_name: graphite-statsd
    ports:
    - '8125:8125/udp'
    - '2003:2003'
    - '80:80'
